---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "6.11.2"

inputs:
- name: hello-hapi
- name: dependency-cache

run:
  path: hello-hapi/ci/scripts/run_tests.sh
