---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
- name: hello-hapi
- name: dependency-cache

run:
  path: hello-hapi/ci/scripts/run_tests.sh
